from collections.abc import Sequence
from typing import Any, Self

class PyRand:
    def __new__(cls) -> Self: ...
    def gen_u32(self) -> int: ...
    def gen_u64(self) -> int: ...
    def gen_f32(self) -> float: ...
    def gen_f64(self) -> float: ...
    def gen_range(self, start: int, end: int) -> int: ...
    def gen_multiple_f64(self, count: int) -> list[float]: ...
    def gen_multiple_u64(self, count: int) -> list[int]: ...
    def seed(self, a: int | None = None) -> None: ...
    def random(self) -> float: ...
    def randint(self, a: int, b: int) -> int: ...
    def uniform(self, a: float, b: float) -> float: ...
    def choice[T](self, seq: Sequence[T]) -> T: ...
    def shuffle(self, x: list[Any]) -> None: ...
    def sample[T](self, population: Sequence[T], k: int) -> list[T]: ...
    def choices[T](self, population: Sequence[T], k: int = 1) -> list[T]: ...
    def gauss(self, mu: float, sigma: float) -> float: ...

def rand_u32() -> int: ...
def rand_u64() -> int: ...
def rand_f32() -> float: ...
def rand_f64() -> float: ...
def rand_range_u64(start: int, end: int) -> int: ...
def random() -> float: ...
def randint(a: int, b: int) -> int: ...
def uniform(a: float, b: float) -> float: ...
def choice[T](seq: Sequence[T]) -> T: ...
def shuffle(x: list[Any]) -> None: ...
def sample[T](population: Sequence[T], k: int) -> list[T]: ...
def choices[T](population: Sequence[T], k: int = 1) -> list[T]: ...
def gauss(mu: float, sigma: float) -> float: ...
